import { Food } from './shared/models/food';
import { tag } from './shared/models/tag';

export const sample_foods: Food[] = [
  {
    id: '1',
    name: 'Pizza Pepperoni',
    cooktime: '10-20',
    price: 199,
    favorite: false,
    stars: 4.5,
    imageurl: 'assets/images/food-1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
    description:
      'Pizza Pepperoni is a classic and beloved pizza variety that features a thin or thick crust topped with zesty tomato sauce, gooey mozzarella cheese.',
  },
  {
    id: '2',
    name: 'Meatball',
    price: 299,
    cooktime: '20-30',
    favorite: true,
    stars: 4.7,
    imageurl: 'assets/images/food-2.jpg',
    tags: ['SlowFood', 'Lunch'],
    description:
      'Meatballs are savory, bite-sized balls of ground meat, typically made from beef, pork, or a combination of both. They are seasoned with herbs, spices, and sometimes breadcrumbs.',
  },
  {
    id: '3',
    name: 'Hamburger',
    price: 255,
    cooktime: '10-15',
    favorite: false,
    description:
      'Hamburgers are an iconic American dish consisting of a juicy and flavorful ground beef patty, usually cooked on a grill or stovetop. Served between two soft buns.',
    stars: 3.5,
    imageurl: 'assets/images/food-3.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id: '4',
    name: 'Fried Potatoes',
    price: 129,
    cooktime: '15-20',
    favorite: true,
    stars: 3.3,
    imageurl: 'assets/images/food-4.jpg',
    tags: ['FastFood', 'Fry'],
    description:
      'Fried potatoes, also known as french fries, are a crispy and indulgent side dish made from sliced or cut potatoes that are deep-fried until golden and delicious. ',
  },
  {
    id: '5',
    name: 'Chicken Soup',
    price: 111,
    description:
      'Chicken soup is a comforting and nourishing dish made by simmering chicken, vegetables, and seasonings in a flavorful broth. It is often hailed for its soothing properties.',
    cooktime: '40-50',
    favorite: false,
    stars: 3.0,
    imageurl: 'assets/images/food-5.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id: '6',
    name: 'Vegetables Pizza',
    price: 199,
    cooktime: '40-50',
    favorite: false,
    description:
      'Vegetable pizza is a delightful and healthy pizza variation that showcases a medley of fresh, colorful vegetables as the primary toppings. It typically features a thin or thick.',
    stars: 4.0,
    imageurl: 'assets/images/food-6.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '7',
    name: 'Vegetables Pizza',
    price: 199,
    cooktime: '40-50',
    favorite: false,
    description:
      ' Vegetables — Green bell pepper, red onion, mushrooms, tomato, and olives are the classic veggie pizza toppings. But it s your pizza, and you can swap if you want to.',
    stars: 4.0,
    imageurl: 'assets/images/my-vegpizza.webp',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '8',
    name: 'NON VEG PIZZA',
    price: 299,
    cooktime: '40-50',
    favorite: false,
    description:
      'Jerked Chicken Pizza. Indulge in the delectable flavours of spicy Jamaican jerk chicken pieces on a creamy pizza that has been cooked to perfection!',
    stars: 4.0,
    imageurl: 'assets/images/my-nonveg.webp',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '9',
    name: 'PIZZA MANIA',
    price: 399,
    cooktime: '40-50',
    favorite: false,
    description:
      'This is a longer card with supporting text below as a natural lead-in to additional content lead-in to additional content lead-in to additional content.',
    stars: 4.0,
    imageurl: 'assets/images/my-pizzamania.webp',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '10',
    name: 'SIDES & BEVERAGES (Coke & Fries)',
    price: 199,
    cooktime: '40-50',
    favorite: false,
    description:
      'Choose different sides and beverages in combo and claim the combo offers!',
    stars: 4.0,
    imageurl: 'assets/images/sides_beverages.webp ',
    tags: ['FastFood'],
  },
  {
    id: '11',
    name: 'PASTA',
    price: 199,
    cooktime: '40-50',
    favorite: false,
    description:
      'The new pasta menus are now available, choose your favourite pasta and enjoy the time with our pasta. ',
    stars: 4.0,
    imageurl: 'assets/images/pasta_new.webp',
    tags: ['FastFood', 'Lunch'],
  },
  {
    id: '12',
    name: 'Burger & Fries',
    price: 199,
    cooktime: '40-50',
    favorite: false,
    description:
      'The Burger and Fries are now available choose your favourite crispy burger with the new peri peri fries.',
    stars: 4.0,
    imageurl: 'assets/images/fries.jpg',
    tags: ['FastFood', 'Lunch', 'Hamburger'],
  },
  {
    id: '13',
    name: 'Pizza Mania 1',
    price: 399,
    cooktime: '40-50',
    favorite: false,
    description:
      'Vegetables — Green bell pepper, red onion, mushrooms, tomato, and olives are the classic veggie pizza toppings. But it s your pizza, and you can swap if you want to.    ',
    stars: 4.0,
    imageurl: 'assets/images/mania.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '14',
    name: 'Pizza Mania 2',
    price: 399,
    cooktime: '40-50',
    favorite: false,
    description:
      'Vegetables — Green bell pepper, red onion, mushrooms, tomato, and olives are the classic veggie pizza toppings. But it s your pizza, and you can swap if you want to.',
    stars: 4.0,
    imageurl: 'assets/images/mania1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '15',
    name: 'Pizza mania 3',
    price: 299,
    cooktime: '40-50',
    favorite: false,
    description:
      'Vegetables — Green bell pepper, red onion, mushrooms, tomato, and olives are the classic veggie pizza toppings. But it s your pizza, and you can swap if you want to.',
    stars: 4.0,
    imageurl: 'assets/images/mania2.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '16',
    name: 'Cheezy VEG PIZZA',
    price: 199,
    cooktime: '40-50',
    favorite: false,
    description:
      'Vegetables — Green bell pepper, red onion, mushrooms, tomato, and olives are the classic veggie pizza toppings. But it s your pizza, and you can swap if you want to.',
    stars: 4.0,
    imageurl: 'assets/images/vegpizza1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '17',
    name: 'VEG PIZZA 2',
    price: 199,
    cooktime: '40-50',
    favorite: false,
    description:
      'Vegetables — Green bell pepper, red onion, mushrooms, tomato, and olives are the classic veggie pizza toppings. But it s your pizza, and you can swap if you want to.',
    stars: 4.0,
    imageurl: 'assets/images/vegpizza2.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '18',
    name: 'Vegetables Pizza 3',
    price: 199,
    cooktime: '40-50',
    favorite: false,
    description:
      'Vegetables — Green bell pepper, red onion, mushrooms, tomato, and olives are the classic veggie pizza toppings. But it s your pizza, and you can swap if you want to. ',
    stars: 4.0,
    imageurl: 'assets/images/vegpizza3.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '19',
    name: 'Non Veg Pizza (Chicken)',
    price: 299,
    cooktime: '40-50',
    favorite: false,
    description:
      'Vegetables — Green bell pepper, red onion, mushrooms, tomato, and olives are the classic veggie pizza toppings. But it s your pizza, and you can swap if you want to.',
    stars: 4.0,
    imageurl: 'assets/images/nonveg1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '20',
    name: 'Non Veg Pizza (crispy chicken)',
    price: 399,
    cooktime: '40-50',
    favorite: false,
    description:
      'Vegetables — Green bell pepper, red onion, mushrooms, tomato, and olives are the classic veggie pizza toppings. But it s your pizza,  and you can swap if you want to.',
    stars: 4.0,
    imageurl: 'assets/images/nonveg2.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '21',
    name: 'Non Veg Pizza 3',
    price: 299,
    cooktime: '40-50',
    favorite: false,
    description:
      'Vegetables — Green bell pepper, red onion, mushrooms, tomato, and olives are the classic veggie pizza toppings. But it s your pizza,and you can swap if you want to.',
    stars: 4.0,
    imageurl: 'assets/images/nonveg3.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
];

export const sample_tags: tag[] = [
  { name: 'All', count: 21 },
  { name: 'FastFood', count: 19},
  { name:'Pizza',count:14},
  {name:'Lunch',count:16},
  {name:'SlowFood',count:2},
  {name:'Hamburger',count:2},
  {name:'Fry',count:1},
  {name:'Soup',count:1}
];
